### ISSUE TITLE
Unable to use this theme with Sylius 1.7

### ISSUE THREAD

**Issue by macintoshplus** [Sylius/BootstrapTheme#25]
After upgrade from Sylius 1.6, I have this error on Front End when I call the product details page:

```
Unable to find one of the following templates: "@SyliusAttribute/Types/text.html.twig", "@SyliusAttribute/Types/default.html.twig" in @SyliusShop/Product/Show/Tabs/_attributes.html.twig at line 9.
```

**Comment by Foksler** [comment]
@macintoshplus some update on this issue?

**Comment by macintoshplus** [comment]
@Foksler Yes, I have reproducted this issue on clean installed instance.

In admin, add a attribute with type 'Text'. Add it on product with a value. Now go to the product page in front office. Your have the error.

**Comment by Foksler** [comment]
@macintoshplus simple fix just to make it work - copy to it old table from ShopBundle/Product/Show/Tabs/Attributes/_list.html.twig

**Comment by quentinCharrier** [comment]
@Foksler I've the same issue and this doesn't seem's to work

**Comment by anthid** [comment]
Sylius 1.7 involves a major rewrite of the template engine, so it isn't a matter of a couple fix here and there.

**Comment by quentinCharrier** [comment]
@macintoshplus 
I've fixed it by copy this file :
`vendor\sylius\sylius\src\Sylius\Bundle\ShopBundle\Resources\views\Product\Show\Tabs\_attributes.html`

into the themes folder : 
` themes\bootstrapTheme\SyliusShopBundle\views\Product\Show\Tabs\_attributes.html`

**Comment by FlashPanther** [comment]
Seems that some calls to "SyliusAttribute" still exist.

vendor/sylius/sylius/src/Sylius/Bundle/ProductBundle/Controller/ProductAttributeController.php
vendor/sylius/bootstrap-theme/SyliusShopBundle/views/Product/Show/Tabs/_attributes.html.twig

It still create an exception for me
